### ISSUE TITLE
Question: Does it stream audio or both?

### ISSUE THREAD

**Issue by devkhan** [smedic/Android-YouTube-Background-Player#9]
Nice project. Does it streams a complete video and plays in the background, OR it only stream audio(if that is possible)?

I'm asking this to save bandwidth.

**Comment by smedic** [comment]
It streams only audio, because I select only audio streams. Of course, if audio is not available, it will stream audio + video. That is up to YT streams.

Check this pull request:
https://github.com/smedic/Android-YouTube-Background-Player/pull/7/commits/2f9e30dcc1be3c847420513b05b6ce474a7dc4d3

I put 1 stream quality, but @arafsheikh added more (141 and 251).

**Comment by smedic** [comment]
You can track network usage in current implementation and later you can change tags to stream both video & audio. After that, compare it to see the difference.
